### ISSUE TITLE
Color scheme

### ISSUE THREAD

**Issue by rgaiacs** [MathML/website#11]
We need a color scheme for our website that is compatible with our logo.
Can we use http://paletton.com/palette.php?uid=52U0u0kijxH8lRvdHHFmfsVqUp6?

**Comment by fred-wang** [comment]
can you explain how it works?

**Comment by rgaiacs** [comment]
> can you explain how it works?

We need a color scheme that is harmonic. I'm not a expert on it but I can ask for a friend that is web designer. What I learned from this friend on a past project is that we need to use colors with good contrast, check http://trace.wisc.edu/contrast-ratio-examples/index.htm.

**Comment by fred-wang** [comment]
Maybe you can try the new color scheme you proposed and let us see how it looks like (the  http://paletton.com/ site is not very explicit about that).

**Comment by rgaiacs** [comment]
http://dev.mathml-association.org/ is updated for comments.

**Comment by fred-wang** [comment]
Is this still relevant?
