### ISSUE TITLE
New header

### ISSUE THREAD

**Issue by rgaiacs** [MathML/website#12]
I was working to improve the header of the website.

For non-mobile devices:

![screen shot 2015-08-08 at 19 09 48](https://cloud.githubusercontent.com/assets/1506457/9152484/31b440e0-3e01-11e5-89aa-9c3dda4fb32c.png)

For mobile devices:

![screen shot 2015-08-08 at 19 09 55](https://cloud.githubusercontent.com/assets/1506457/9152483/25942cda-3e01-11e5-877e-f047b91a3b03.png)

You can test it using https://github.com/rgaiacs/website/tree/dev.

@fred-wang Can you give me your feedback?

@dginev I need a little help with CSS magic. Can you help me?

**Comment by fred-wang** [comment]
- I believe you should use the *-text-as-path version of the logo.
- white text over very light green is not nice to read

**Comment by dginev** [comment]
What happened to the final "n" of "association"? I can try to help a little tomorrow.

**Comment by fred-wang** [comment]
> What happened to the final "n" of "association"? I can try to help a little tomorrow.

The bad fonts are used. That's why I suggested to use the version with "text drawn with paths".
https://mathml.github.io/logo/

**Comment by fred-wang** [comment]
Actually, it seems that nothing is generated at the moment on http://dev.mathml-association.org/logo/

**Comment by fred-wang** [comment]
> The bad fonts are used. That's why I suggested to use the version with "text drawn with paths".
Done in https://github.com/MathML/website/commit/c3333336881ac8e30ef158c3c214f736a5f8fca0

**Comment by fred-wang** [comment]
@rgaiacs Maybe the logo makes the header too large. Perhaps we should set its img@width to a smaller value like ~400px ?

**Comment by rgaiacs** [comment]
Done at #24.
