### ISSUE TITLE
Meetings archive

### ISSUE THREAD

**Issue by rgaiacs** [MathML/website#13]
Are we going to store the minutes at GitHub wiki or at the website?

**Comment by fred-wang** [comment]
I think the minutes are on the website.

The wiki is more for our "internal" use (e.g. prepare the agenda)

**Comment by fred-wang** [comment]
BTW, there is a problem with the meeting page:

If you are on http://dev.mathml-association.org/meetings/meetings.html and click "meetings" again, you arrive on http://dev.mathml-association.org/meetings/meetings/meetings.html

**Comment by rgaiacs** [comment]
> BTW, there is a problem with the meeting page:
>
> If you are on http://dev.mathml-association.org/meetings/meetings.html and click "meetings" again, you arrive on http://dev.mathml-association.org/meetings/meetings/meetings.html

Fixed by https://github.com/MathML/website/pull/16
