### ISSUE TITLE
Protect email address against spams

### ISSUE THREAD

**Issue by fred-wang** [MathML/website#23]
@rgaiacs do you think all the references to directors@mathml-association.org should be written e.g. directors AT mathml DASH association DOT org to minimize spams by bots?

**Comment by rgaiacs** [comment]
> @rgaiacs do you think all the references to directors@mathml-association.org should be written e.g. directors AT mathml DASH association DOT org to minimize spams by bots?

My **personal** preference is to make easy for people to contact us even it means to get email from spam bots since smart bots will also search for `foo AT bar DOT something`. But I'm OK to use `directors AT mathml DASH association DOT org` if people want to.

**Comment by fred-wang** [comment]
closing
