### ISSUE TITLE
Improve error for invalid address

### ISSUE THREAD

**Issue by fred-wang** [MathML/website#28]
mathml-association.org/page-not-found.html

returns 

500 Internal Server Error
nginx/1.2.1

**Comment by fred-wang** [comment]
Assigned to Raniere.

**Comment by rgaiacs** [comment]
> mathml-association.org/page-not-found.html returns 500 Internal Server Error.

This happens because there is no file `page-not-found.html`. Need to create one.

**Comment by fred-wang** [comment]
I don't think it's a problem with the exact page name. It also happens with

http://mathml-association.org/my-arbitrary-page.html

**Comment by rgaiacs** [comment]
I need to setup https://www.nginx.com/resources/admin-guide/nginx-web-server/#errors at the server but also have a page for the error.

**Comment by rgaiacs** [comment]
Fixed.
