### ISSUE TITLE
number the FAQ and give it a toc

### ISSUE THREAD

**Issue by kohlhase** [MathML/website#30]
The FAQ is growing, therefore I think we should have the questions numbered and it should have a table of contents. I am not sure how to do that in markdown.

**Comment by rgaiacs** [comment]
> I think we should have the questions numbered  and it should have a table of contents.

I'm OK with that.

> I am not sure how to do that in markdown.

Markdown hasn't a syntax for table of contents. We can use https://github.com/toshimaru/jekyll-toc or something similar.

**Comment by kohlhase** [comment]
that is a very good idea. I suspect that we will need tocs in other situations as well.

**Comment by fred-wang** [comment]
Apparently kramdown (the markdown version we use) has built-in support for toc, so I've used that: http://kramdown.gettalong.org/converter/html.html#toc

I've done a minimal change for the numbering and toc, here is how it looks like:
http://mathml-association.org/faq.html

**Comment by kohlhase** [comment]
nice, thanks this is much better (and more scalable).
