### ISSUE TITLE
put the officers into the web site. 

### ISSUE THREAD

**Issue by kohlhase** [MathML/website#31]
I am not sure how to best do that.

One thing would be to add the role to http://mathml-association.org/directors.html I guess, but then we should probably have a page "officers" under the "about" tab that gives the organization structure (stating the offices and the current officers). 

We could/should maybe also have e-mail redirects like ```president@mathml-association.org``` and (more important) ```treasurer@``` and ```secretary@```. 
@fred-wang @dginev @physikerwelt @rgaiacs what do you think?

**Comment by fred-wang** [comment]
The menu layout is currently done to have "at most 4 items per submenu". Also, on mobile all the menu are grouped into one big list. So I'd prefer avoiding new items in the submenus...

What about replacing "Directors" with a "People" or "Team" page that will then redirect to other pages:
1) Directors
2) Officiers
3) Advisory Board

**Comment by kohlhase** [comment]
> So I'd prefer avoiding new items in the submenus...

I suspected that and agree. Your solution sounds good to me.

**Comment by fred-wang** [comment]
https://github.com/MathML/website/pull/33

@rgaiacs Can you create the three addresses proposed by Michael?

**Comment by kohlhase** [comment]
I think we should also have a mailing list or alias ```info@mathml-association.org``` (forward to our secretary) for contact and put this up at http://mathml-association.org/contact.html

**Comment by fred-wang** [comment]
So I guess info@ would replace all the directors@ currently on the website?

**Comment by kohlhase** [comment]
yes, that gives us a way of keeping directors@ to its original purpose.

**Comment by fred-wang** [comment]
OK, I'm preparing a pull request for that.

**Comment by kohlhase** [comment]
while you are at it, you might want to rename people/officiers.md to people/officers.md (I already repaired a related typo in the text).

**Comment by kohlhase** [comment]
and I think we do not need pull requests for such simple changes.

**Comment by fred-wang** [comment]
OK, but I can't create the email addresses myself, so wanted to wait Raniere before merging. Will fix the typo first

**Comment by fred-wang** [comment]
OK, I opened https://github.com/MathML/website/pull/34

**Comment by rgaiacs** [comment]
> @rgaiacs Can you create the three addresses proposed by Michael?

<table class="gtable">        <thead>
    <tr>            
            <th data-value="source" style="width:478px"><a href="?page=1&amp;order_by=source%20desc">Address</a><span data-perpage="6" class="total" data-allpages="6"> (6/6)</span><a href="?page=1&amp;order_by=source%20desc" class="sort desc"></a>            </th>            
            <th data-value="destinations" style="width:400px">Forwarded to            </th>                </tr></thead>
        <tfoot>    <tr>
        <th colspan="4">
            <div class="left">            </div>
            <div class="right">
    <div class="limiter">
    </div>            <div class="pager">            </div>            </div>
        </th>
    </tr></tfoot>
        <tbody class="ajax_content">
    <tr>            
            <td class="column-source">        <a class="login" href="/admin/domain/4626664/email/forward/update/forward-directors" data-source="directors">directors@</a></td>            
            <td class="column-destinations">            <a class="show_other_destinations link-more clickable open" href="#other_directors">raniere@rgaiacs.com            </a>
            <div style="display: block;" id="other_directors" class="js-hide other_destinations">d.ginev@jacobs-university.de<br>fred.wang@free.fr<br>m.kohlhase@jacobs-university.de<br>physik@physikerwelt.de            </div></td>            
    <tr>            
            <td class="column-source">        <a class="login" href="/admin/domain/4626664/email/forward/update/forward-info" data-source="info">info@</a></td>            
            <td class="column-destinations">            <a class="show_other_destinations link-more clickable open" href="#other_info">raniere@rgaiacs.com            </a>
            <div style="display: block;" id="other_info" class="js-hide other_destinations">d.ginev@jacobs-university.de            </div></td>            

    <tr>            
            <td class="column-source">        <a class="login" href="/admin/domain/4626664/email/forward/update/forward-president" data-source="president">president@</a></td>            
            <td class="column-destinations">m.kohlhase@jacobs-university.de</td>            

    <tr>            
            <td class="column-source">        <a class="login" href="/admin/domain/4626664/email/forward/update/forward-secretary" data-source="secretary">secretary@</a></td>            
            <td class="column-destinations">d.ginev@jacobs-university.de</td>            

    <tr>            
            <td class="column-source">        <a class="login" href="/admin/domain/4626664/email/forward/update/forward-treasurer" data-source="treasurer">treasurer@</a></td>            
            <td class="column-destinations">raniere@rgaiacs.com</td>            

    <tr>            
            <td class="column-source">        <a class="login" href="/admin/domain/4626664/email/forward/update/forward-vice-president" data-source="vice-president">vice-president@</a></td>            
            <td class="column-destinations">fred.wang@free.fr</td>            
</tbody>    </table>

**Comment by kohlhase** [comment]
Wonderful, just tested the directors address, works.

**Comment by fred-wang** [comment]
I think info@ should also go to Moritz, as he was interested in PR
