### ISSUE TITLE
Menu and Safari 8.0.8

### ISSUE THREAD

**Issue by rgaiacs** [MathML/website#35]
Someone email us saying that

> Your menu items (Manifesto, News, About, etc.) do not appear in my
> browser. They only appear when I hover over them. I¹m using Safari 8.0.8.

**Comment by fred-wang** [comment]
linear-gradient is not supported by all browser so it is best to use a standard background as a fallback.

https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient?redirectlocale=en-US&redirectslug=CSS%2Flinear-gradient#Cross-browser_gradients

Fixed.
