### ISSUE TITLE
Add the friends application template in the HTML page for copy & paste

### ISSUE THREAD

**Issue by fred-wang** [MathML/website#40]
I suspect that the mailto: link does not work well with some webmails, so we would need to provide an alternative way to access the template.

**Comment by physikerwelt** [comment]
@HowardCohl reported exactly the problem you mention.
For now one could use the text from #39 

In general I think we should simply add a form mailer to our website i.e. `<form action="MAILTO:bla" method="post" enctype="text/plain">`

**Comment by fred-wang** [comment]
> In general I think we should simply add a form mailer to our website i.e. <form action="MAILTO:bla" method="post" enctype="text/plain">

Just a reminder: It was the original idea and it is still the plan to create a form, but setting all these things up is less straightforward than just letting people use their mail client... A quick internet search seems to indicate that doing form action="MAILTO:.." is not always a good idea, so let's continue with manual "email" until we have a proper mail submission form (but feel free to help Raniere on this).

**Comment by HowardCohl** [comment]
By the way, the template that @physikerwelt mailed me is this

```
[Please remove the text in brackets and replace it with the requested content.] 
Dear MathML directors, 
I'm applying to become a MathML Friend. Please find my information below. 
Full name: [required] 
Brief introduction: [required ; for example 'PhD student in the Department of Physics at Harvard University'] 
More about myself: [optional ; describe your involvement in MathML, why you
want to become a friend, provide a link to your homepage or to social media
accounts, indicate where you live, etc.]
I hereby state that I read the terms of the Affiliates document [1], that I
want to become a "MathML Friend" and that I fulfill all the requirements. In
particular, I attest that I am 18 years of age or older, that I read the
MathML Manifesto [2], and that I agree with it. I also give you the
permission to publish the information provided in the 'required' fields above.

[sign by giving your name]

[1] http://mathml-association.org/legal-documents/affiliates.html
[2] http://mathml-association.org/legal-documents/manifesto.html
```

and this should be mailed to: directors@mathml-association.org

**Comment by fred-wang** [comment]
The template text is now available on the Friends page. I'm removing HowardCohl's comment to avoid to confuse people.

**Comment by HowardCohl** [comment]
I still can't access the template from the web page:

http://mathml-association.org/affiliates/friends.html

At least it was emailed to me by @physikerwelt so I could actually access it and use it. Other users using firefox I don't think will be able to access it.

**Comment by fred-wang** [comment]
> using this template (alternatively, try this link)

Did you try the alternative link?

**Comment by HowardCohl** [comment]
oh, I didn't see that. Yes that works well. :+1:

**Comment by fred-wang** [comment]
no problem. I hope we'll have a beautiful form in the future...
