### ISSUE TITLE
Simplify friend registration process

### ISSUE THREAD

**Issue by physikerwelt** [MathML/website#49]
I evaluated the friend application process.
My experience is that people postpone sending the friends application form.
Many of them are generally open to write a introduction in the sense of
```
More about myself: [optional ; describe your involvement in MathML, why you want to become a friend, provide a link to your homepage or to social media accounts, indicate where you live, etc.]
```
However, this takes too long to do it on the fly.
Maybe we should reduce that field into two.
```
Link: [optional ; provide a link to your homepage or to social media accounts]
```
And ask for additional informatin if that's required in the confirmation phase. I think it's unreasonable to let people write this "More about myself" if the information is never published.
Instead we could encourage them to introduce themselfes on the friends mailinglist.

**Comment by physikerwelt** [comment]
ping @MathML/owners

**Comment by fred-wang** [comment]
That makes sense. However, people do not necessarily have a public profile or more generally (as was your concerned in the past with the public mailing list) may not want to post public personal data. So what about just:

More about myself: [optional ; longer introduction, homepage or social media accounts ]

**Comment by physikerwelt** [comment]
@fred-wang what should we do with the "longer introduction"? Where should we store the data? Who is allowed to read it and who is not? According to german law "§ 3a Bundesdatenschutzgesetz" we should only collect data that is needed.
However, we use the link to link the name to the homepage in the friend list. So maybe:
```
Link: [optional ; provide a link to your homepage or to social media accounts if you want that your name is linked to that URL]
```

**Comment by fred-wang** [comment]
> what should we do with the "longer introduction"?

Just like the link this is just an optional way for the Friend to give more details and a more "friendly" and "human" introduction. This is especially useful if they are apply by themselves and we don't know them at all.

> Where should we store the data? Who is allowed to read it and who is not? 

This is already indicated: "Note that your message will be stored on our server and will only be accessible to the directors." and "If your application is approved, your name and the brief introduction will be used on this Friends page and for public announcements. Also, note that your email address will be used for communication with the MathML Association"

> According to german law "§ 3a Bundesdatenschutzgesetz" we should only collect data that is needed.
I'm not sure what you mean here. The association is under the NY state law.

**Comment by fred-wang** [comment]
BTW, I'd also like to note that the link was not supposed to be published. This was a benefit for Bronze Sponsor but Friends only have their name according to http://mathml-association.org/legal-documents/affiliates.html

**Comment by fred-wang** [comment]
So just to clarify, you are really asking two things here:
- Remove the optional "more about yourself" entry (which is fine)
- Add an optional "link" entry + the benefit to have this link published (which implies updating the page description, amending the affiliates document, voting and informing friends)

**Comment by physikerwelt** [comment]
Do you suggest to remove the links?
I suggested to fetch additional information from the applicant indivually via email, instead of collecting it in advance enven though, we might not need it.

**Comment by physikerwelt** [comment]
note that all friends besides Hang Yuan already have links http://mathml-association.org/affiliates/friends.html

**Comment by fred-wang** [comment]
> Do you suggest to remove the links?
The initial idea was to have increasing benefits for friends and sponsors. So for friends the link was not published and actually the "one-sentence introduction" was only for grouped announcements. I thought the friends page to be something like https://www.mozilla.org/credits/. We should probably reconsider the initial idea and amend the documents, since that's not the approach we actually followed. At the moment Friends have more benefits than Bronze sponsor in term of website publicity...

> I suggested to fetch additional information from the applicant indivually via email, instead of collecting it in advance enven though, we might not need it.

Yes, that makes sense.

**Comment by physikerwelt** [comment]
thank you for sharing that link. I would recommend to mozilla to allow for links on that page since the name is not unique and it can be really annoying if you get mixed up with somebody else. However, we should focus that our friends list becomes as long as the mozilla list in the first place.

**Comment by fred-wang** [comment]
So to summarize the idea for future vote if we follow the current practice:

1) Affiliates document:

"name displayed on the website of the MathML Association in the list of “MathML Friends”"
Should be changed to
"name, brief introduction and optional link displayed on the website of the MathML Association in the list of “MathML Friends”"

2) Template:
"More about myself: ..."
Should be changed to
"Link: [optional ; homepage or social media accounts]"

3) Friends instruction:
"your name and the brief introduction will be used"
Should be changed to
"your name, the brief introduction and optional link will be used"

**Comment by physikerwelt** [comment]
@fred-wang thank you!
:+1:

**Comment by physikerwelt** [comment]
a little comment about the Link I'd prefer 
Link: [optional ; provide a link to your homepage or to social media account, if you want that your name is linked to that URL.]
which fits better to the rest of the instruction

**Comment by dginev** [comment]
:+1:

**Comment by fred-wang** [comment]
OK, can you submit a pull request to vote on?

**Comment by physikerwelt** [comment]
how did you create the formdata?
urlencode?

On Sat, Jan 9, 2016 at 4:23 PM, Frédéric Wang <notifications@github.com>
wrote:

> OK, can you submit a pull request to vote on?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MathML/website/issues/49#issuecomment-170251649>.
>



-- 
Moritz Schubotz
TU Berlin, Fakultät IV
DIMA - Sekr. EN7
Raum EN742
Einsteinufer 17
D-10587 Berlin
Germany

Tel.: +49 30 314 22784
Mobil.: +49 1578 047 1397
Fax:  +49 30 314 21601
E-Mail: schubotz@tu-berlin.de
Skype: Schubi87
ICQ: 200302764
Msn: Moritz@Schubotz.de
